### ISSUE TITLE
tests fail without fs_peptide data

### ISSUE THREAD

**Issue by momeara** [mdtraj/tftraj#3]
Many of the tests require `fs_peptide/fs-peptide.pdb`
but it looks like from the .gitignore that this directory is excluded from the repo

Would it be possible to include the test data in the repo, or alternatively host the test data remotely and give a link to it, so the tests can be run?

**Comment by cxhernandez** [comment]
That's no good! For now, you can find that pdb [here](https://github.com/msmbuilder/msmb_data/blob/master/msmb_data/fs_peptide/fs-peptide.pdb), along with a handful of other datasets in [msmb_data](https://github.com/msmbuilder/msmb_data).

~@mdtraj/developers: maybe we should look into running the tests on data from `msmb_data`?~

**Comment by mpharrigan** [comment]
Hi @momeara 

The test data can be downloaded here https://figshare.com/articles/Fs_MD_Trajectories/1030363

It's too big (probably) to include it in the repo, but there should definitely be a link and documentation

@cxhernandez note this repo is tftraj not mdtraj

**Comment by cxhernandez** [comment]
LOL my bad

**Comment by momeara** [comment]
cheers!
