### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by momeara** [mdtraj/tftraj#5]
I am getting an `Illegal instruction (core dumped)` error trying to run `pairwise_msd`.

My setup

    $ uname -r
    2.6.32-573.7.1.el6.centos.plus.x86_64

    $ cat /proc/cpuinfo
    # ...
    processor       : 23
    vendor_id       : AuthenticAMD
    cpu family      : 16
    model           : 9
    model name      : AMD Opteron(tm) Processor 6176
    stepping        : 1
    cpu MHz         : 2300.000
    cache size      : 512 KB
    physical id     : 1
    siblings        : 12
    core id         : 5
    cpu cores       : 12
    apicid          : 43
    initial apicid  : 27
    fpu             : yes
    fpu_exception   : yes
    cpuid level     : 5
    wp              : yes
    flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nonstop_tsc extd_apicid amd_dcm pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr npt lbrv svm_lock nrip_save pausefilter
    bogomips        : 4600.81
    TLB size        : 1024 4K pages
    clflush size    : 64
    cache_alignment : 64
    address sizes   : 48 bits physical, 48 bits virtual
    power management: ts ttp tm stc 100mhzsteps hwpstate

    $ python --version
    Python 2.7.11 :: Anaconda 4.1.0 (64-bit)

    $ pip freeze | grep 'tensorflow=='
    tensorflow==1.1.0

    $ gcc --version
    gcc (GCC) 4.9.3
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    $ git rev-parse HEAD
    f3715c1efc7a2ad5ea6821a445c17c1220cc381f

fail.py:

    import numpy as np
    import tensorflow as tf
    import tftraj.rmsd_op

    rmsd = tftraj.rmsd_op.load()
    prmsd, _ = rmsd.pairwise_msd(np.random.randn(11, 12, 3), np.random.randn(11, 12, 3))
    sess = tf.Session()
    r1 = sess.run(prmsd)

output:
```
2017-06-22 13:28:14.896896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] Found device 0 with properties:
name: Quadro K600
major: 3 minor: 0 memoryClockRate (GHz) 0.8755
pciBusID 0000:05:00.0
Total memory: 1023.31MiB
Free memory: 1006.57MiB
2017-06-22 13:28:14.896978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] DMA: 0
2017-06-22 13:28:14.896995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 0:   Y
2017-06-22 13:28:14.897020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Ignoring visible gpu device (device: 0, name: Quadro K600, pci bus id: 0000:05:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 5.2.
2017-06-22 13:28:14.914959: I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 1 visible devices
2017-06-22 13:28:14.915022: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 24 visible devices
2017-06-22 13:28:14.928024: I tensorflow/compiler/xla/service/service.cc:183] XLA service 0x3155440 executing computations on platform Host. Devices:
2017-06-22 13:28:14.928078: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (0): <undefined>, <undefined>
2017-06-22 13:28:14.928132: I tensorflow/compiler/xla/service/platform_util.cc:116] StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 3.0
Illegal instruction (core dumped)
```

I was able to build the cmake Debug build and run it through gdb. Here final frames in the backtrace after it exited:
```
bt full
(gdb)bt full
#0  0x00007fffc8adfedd in _mm_set_ps (__W=-0.141467422, __X=0.0819387883,
    __Y=0.47255379, __Z=0.982174039)
    at /mnt/nfs/home/momeara/opt/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/xmmintrin.h:946
No locals.
#1  msd_atom_major (nrealatoms=12, npaddedatoms=12, a=0x2b165b0, b=0x2b168c0,
    G_a=29.4467869, G_b=41.7831383, computeRot=1, rot=0x2b15cf4)
    at /mnt/nfs/work/momeara/sea/DeepSEA/tftraj/tftraj/tftraj/rmsd/theobald_rmsd.c:599
        niters = 3
        k = 2
        masks = {{1, 1, 1, 1}, {1, 0, 0, 0}, {1, 1, 0, 0}, {1, 1, 1, 0}}
        mask = 0x7fffc8ae2280 <masks>
        M = {0 <repeats 12 times>}
        xx = {0.949453235, 0.255332381, -0.637079537, 0.521678805}
        xy = {-0.17454204, 0.172681689, 1.85346425, -1.36961818}
        xz = {2.00161672, -0.0533463359, 0.108790681, -0.108983845}
        yx = {0.0342159718, 1.50141954, 1.40289485, 1.15366089}
        yy = {-0.181131706, 1.08786595, 2.57034063, -3.45596552}
        yz = {0.703198195, -0.211374387, 0.327231675, -0.79959476}
        zx = {-0.416336119, -1.12106347, -0.514304578, 0.853266656}
        zy = {0.287990808, -0.685520351, -1.3381629, -2.24499702}
        zz = {-1.64092231, 0.336825013, -0.153695777, -0.184567422}
        ax = {-0.673893631, 0.351444364, -0.480079532, -0.728970349}
        ay = {-0.35596931, 1.98144484, -1.04628062, -0.434962094}
        az = {0.696642339, -1.62842941, 0.508751988, -1.17901564}
        bx = {0.34415102, -1.19913781, -0.61511904, 0.371415734}
        by = {0.432718605, -0.829774797, -1.28510427, -0.735616863}
        bz = {-1.06465352, 0.223991618, -0.156951144, 0.235610038}
        t0 = {-0.175853804, 1.45909011, 1.26503122, 0.137022585}
        t1 = {-0.221109942, 1.00965571, 2.64289808, -0.271383554}
        t2 = {0.544015169, -0.272549152, 0.322779953, 0.0869211853}
```

[(Gough,2005)](http://www.network-theory.co.uk/docs/gccintro/gccintro_64.html
) suggests that it may be a compatibility issue with the processor.  
I tried adding each of these flags to `cmake-build-release` and they all gave the same error.
```
CMAKE_C_FLAGS:STRING=-mmmx -march=native
CMAKE_C_FLAGS:STRING=-march=native
```

I also had access to an intel machine:
```
$ cat /proc/cpuinfo
processor       : 31
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
stepping        : 4
microcode       : 1064
cpu MHz         : 1200.000
cache size      : 20480 KB
physical id     : 1
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 47
initial apicid  : 47
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips        : 3999.43
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

Recompiling the `tftraj` library and running the above `fail.py` but with `debug=False` crashed with an `Illegal Instruction` error too.

**Comment by rmcgibbo** [comment]
I'm not sure about your later intel machine. However for the first AMD machine, I believe the issue is that your CPU doesn't support SSE3 instructions, which are required.

**Comment by momeara** [comment]
Ok, that makes sense.  It tried it again on the Intel machine and it works there!

Cheers
